<?php
session_start();
header('Content-Type: text/html; charset=shift_JIS');

// ログイン状態チェック
if (!isset($_SESSION['username'])) {
    header("Location: logout.php");
    exit;
}
?>

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="shift_JIS">
        <title>メイン</title>
        <link rel= "stylesheet" href="font.css">
        <script src="script.js"></script>
    </head>
    <body>
        <h1>メイン画面</h1>
        <p>ようこそ<u><?php echo htmlspecialchars($_SESSION['username'], ENT_QUOTES); ?></u>さん</p>
        <pre>
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃<span class="font">若若若若若若</span>乃乃乃乃乃乃若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若若乃乃乃乃乃乃若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若乃乃乃乃乃乃乃若若若若若乃乃乃乃若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月月月月月月月月月月月月月月月月乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月月月乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃若若若若乃乃乃乃若若若若若乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月月月乃乃乃乃乃
        乃乃乃乃乃乃若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃
        乃乃乃乃乃若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃若若乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃若若若乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月月月月月月月月月月月月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若若乃乃乃乃乃乃乃乃乃乃乃若乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃若若若若若乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月月月月月月月月月月月月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃若若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃若若若乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃若若若乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃若若若乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月乃乃乃乃乃乃
        乃乃乃乃乃乃乃若若若乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃乃月月月月月月月月月月月乃乃乃乃乃乃
        乃乃乃乃乃乃若若若乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月月月月乃乃乃乃乃乃
        乃乃乃乃乃若若若乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月月乃乃乃乃乃乃乃
        乃乃乃乃若若乃乃乃乃乃乃乃乃乃若若若若若若若若若若若若若若若若若若若乃乃乃乃乃乃乃乃乃乃乃乃月月乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月月月乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃若若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃月月月乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃若若乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃
        乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃乃


        </pre>
        <ul>
            <li><a href="logout.php">ログアウト</a></li>
        </ul>
    </body>
</html>